{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "chart.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
